// 表单属性【右面板】

export const formConf = {
  formRef: 'quasarForm',
  formModel: 'form',
  tableId: 'main_',
  tableName: '主表',
  labelPosition: 'top',
  labelWidth: 100,
  disable: false,
  span: 12,
  formBtns: true,
  formSize: 'dialog_card',
};
// 默认页面数据
export const formData = {
  idGlobal: 100, drawingList: [], formConf, grid: {},
};

// 常用控件
export const commonComponents = [
  {
    // 组件的自定义配置
    config: {
      label: '单行文本',
      labelWidth: null,
      showLabel: true,
      changeTag: true,
      tag: 'q-input',
      tagIcon: 'input',
      required: true,
      layout: 'colFormItem',
      span: 6,
      // 正则校验规则
      rule: '',
      regList: [],
      defaultType: 'custom',
      defaultValue: undefined,
      expression: undefined,
      relatedForm: '',
      relatedColumn: '',
      relatedFilter: [],
    },
    type: 'text',
    prefix: '',
    suffix: '',
    mask: '',
    fillMask: '',
    hint: null,
    hideHint: false,
    // 组件的插槽属性
    slot: {
      prepend: '',
      append: '',
    },
    // 其余的为可直接写在组件标签上的属性
    autofocus: false,
    outlined: true,
    dense: true,
    readonly: false,
    disable: false,
    counter: false,
    placeholder: '请输入',
    clearable: true,
    maxlength: null,
    db: {
      dbType: 'varchar',
      dbLength: 255,
      dbScale: 0,
      dbNull: true,
      dbPrimary: false,
      dbUnique: false,
    },
  },
  {
    // 组件的自定义配置
    config: {
      label: '多行文本',
      labelWidth: null,
      showLabel: true,
      changeTag: false,
      tag: 'q-input',
      tagIcon: 'textarea',
      required: true,
      layout: 'colFormItem',
      span: 12,
      // 正则校验规则
      rule: '',
      regList: [],
      defaultType: 'custom',
      defaultValue: undefined,
      relatedForm: '',
      relatedColumn: '',
      relatedFilter: [],
    },
    type: 'textarea',
    prefix: '',
    suffix: '',
    hint: null,
    hideHint: false,
    // 组件的插槽属性
    slot: {
      prepend: '',
      append: '',
    },
    // 其余的为可直接写在组件标签上的属性
    autofocus: false,
    outlined: true,
    dense: true,
    readonly: false,
    disable: false,
    counter: false,
    placeholder: '请输入',
    clearable: true,

    maxlength: null,
    step: 1,
    db: {
      dbType: 'varchar',
      dbLength: 255,
      dbScale: 0,
      dbNull: true,
      dbPrimary: false,
      dbUnique: false,
    },
  },
  {
    // 组件的自定义配置
    config: {
      label: '数值',
      labelWidth: null,
      showLabel: true,
      changeTag: false,
      tag: 'q-input',
      tagIcon: 'number',
      required: true,
      layout: 'colFormItem',
      span: 6,
      // 正则校验规则
      rule: '',
      regList: [],
      defaultType: 'custom',
      defaultValue: undefined,
      relatedForm: '',
      relatedColumn: '',
      relatedFilter: [],
    },
    type: 'number',
    prefix: '',
    suffix: '',
    hint: null,
    hideHint: false,
    // 组件的插槽属性
    slot: {
      prepend: '',
      append: '',
    },
    // 其余的为可直接写在组件标签上的属性
    autofocus: false,
    outlined: true,
    dense: true,
    readonly: false,
    disable: false,
    counter: false,
    placeholder: '请输入',
    clearable: true,

    maxlength: null,
    min: 0,
    max: 100,
    step: 1,
    db: {
      dbType: 'int',
      dbLength: 255,
      dbScale: 0,
      dbNull: true,
      dbPrimary: false,
      dbUnique: false,
    },
  },
  {
    config: {
      label: '下拉选择',
      showLabel: true,
      labelWidth: null,
      tag: 'q-select',
      tagIcon: 'select',
      layout: 'colFormItem',
      span: 6,
      required: true,
      rule: '',
      regList: [],
      changeTag: false,
      optionSourceType: 'custom',
      optionForm: '',
      optionLabel: '',
      optionValue: '',
      optionFilter: [],

      sysDicCode: '',
      sysDicName: '',
      defaultType: 'custom',
      defaultValue: undefined,
      relatedForm: '',
      relatedColumn: '',
      relatedFilter: [],

      logicList: [],
    },
    prefix: '',
    suffix: '',
    hint: null,
    hideHint: false,
    outlined: true,
    dense: true,
    optionsDense: true,
    emitValue: true,
    mapOptions: true,
    readonly: false,
    disable: false,
    counter: false,
    clearable: true,
    filterable: false,
    multiple: false,
    options: [{
      label: '选项一',
      value: '1',
    }, {
      label: '选项二',
      value: '2',
    }],
    db: {
      dbType: 'varchar',
      dbLength: 255,
      dbScale: 0,
      dbNull: true,
      dbPrimary: false,
      dbUnique: false,
    },
  },
  {
    config: {
      label: '单选框组',
      labelWidth: null,
      showLabel: true,
      tag: 'q-option-group',
      tagIcon: 'radio',
      changeTag: false,
      defaultValue: null,
      layout: 'colFormItem',
      span: 6,
      optionSourceType: 'custom',
      rule: '',
      regList: [],
      required: true,
      border: false,
    },
    color: 'primary',
    options: [{
      label: '选项一',
      value: '1',
    }, {
      label: '选项二',
      value: '2',
    }],
    inline: true,
    disable: false,
    db: {
      dbType: 'varchar',
      dbLength: 255,
      dbScale: 0,
      dbNull: true,
      dbPrimary: false,
      dbUnique: false,
    },
  },
  {
    config: {
      label: '多选框',
      tag: 'q-checkbox',
      tagIcon: 'checkbox',
      defaultValue: '0',
      span: 2,
      showLabel: true,
      labelWidth: null,
      layout: 'colFormItem',
      optionSourceType: 'custom',
      required: true,
      rule: '',
      regList: [],
      changeTag: false,
      border: false,
    },
    inline: true,
    color: 'primary',
    type: 'checkbox',
    style: {},
    disable: false,
    trueValue: '1',
    falseValue: '0',
    db: {
      dbType: 'varchar',
      dbLength: 1,
      dbScale: 0,
      dbNull: true,
      dbPrimary: false,
      dbUnique: false,
    },
  },
  {
    config: {
      label: '开关',
      tag: 'q-toggle',
      tagIcon: 'switch',
      defaultValue: '1',
      span: 2,
      showLabel: true,
      labelWidth: null,
      layout: 'colFormItem',
      required: true,
      rule: '',
      regList: [],
      changeTag: false,
    },
    color: 'primary',
    style: {},
    disable: false,
    trueValue: '1',
    falseValue: '0',
    db: {
      dbType: 'varchar',
      dbLength: 1,
      dbScale: 0,
      dbNull: true,
      dbPrimary: false,
      dbUnique: false,
    },
  },
  {
    config: {
      label: '滑块',
      tag: 'q-slider',
      tagIcon: 'slider',
      defaultValue: 50,
      span: 6,
      showLabel: true,
      layout: 'colFormItem',
      labelWidth: null,
      required: true,
      rule: '',
      regList: [],
      changeTag: false,
    },
    dense: false,
    label: true,
    markers: false,
    vertical: false,
    labelAlways: true,
    reverse: false,
    disable: false,
    min: 0,
    max: 100,
    step: 1,
    color: 'red',
    labelColor: 'red',
    labelTextColor: 'white',
    db: {
      dbType: 'int',
      dbLength: 255,
      dbScale: 0,
      dbNull: true,
      dbPrimary: false,
      dbUnique: false,
    },
  },
  {
    config: {
      label: '时间选择',
      tag: 'q-input',
      tagIcon: 'time',
      defaultValue: null,
      span: 6,
      showLabel: true,
      layout: 'colFormItem',
      labelWidth: null,
      required: true,
      rule: '',
      regList: [],
      changeTag: false,
    },
    placeholder: '请选择',
    type: 'time',
    autofocus: false,
    outlined: true,
    dense: true,
    disable: false,
    clearable: true,
    db: {
      dbType: 'time',
      dbLength: 10,
      dbScale: 0,
      dbNull: true,
      dbPrimary: false,
      dbUnique: false,
    },
  },
  {
    config: {
      label: '日期选择',
      tag: 'q-input',
      tagIcon: 'date',
      defaultValue: null,
      showLabel: true,
      labelWidth: null,
      span: 6,
      layout: 'colFormItem',
      required: true,
      rule: '',
      regList: [],
      changeTag: false,
    },
    placeholder: '',
    type: 'date',
    autofocus: false,
    outlined: true,
    dense: true,
    disable: false,
    clearable: true,
    readonly: false,
    db: {
      dbType: 'date',
      dbLength: 10,
      dbScale: 0,
      dbNull: true,
      dbPrimary: false,
      dbUnique: false,
    },
  },
  {
    config: {
      label: '评分',
      tag: 'q-rating',
      tagIcon: 'rate',
      defaultValue: 0,
      span: 6,
      showLabel: true,
      labelWidth: null,
      layout: 'colFormItem',
      required: true,
      rule: '',
      regList: [],
      changeTag: false,
    },
    color: 'primary',
    style: {},
    max: 5,
    size: '2em',
    icon: 'star_border',
    disable: false,
    db: {
      dbType: 'int',
      dbLength: 8,
      dbScale: 0,
      dbNull: true,
      dbPrimary: false,
      dbUnique: false,
    },
  },
  {
    config: {
      label: '颜色选择',
      tag: 'input-color',
      tagIcon: 'color',
      span: 6,
      defaultValue: null,
      showLabel: true,
      labelWidth: null,
      layout: 'colFormItem',
      required: true,
      rule: '',
      regList: [],
      changeTag: false,
    },
    'show-alpha': false,
    'color-format': '',
    disable: false,
    size: 'medium',
    db: {
      dbType: 'varchar',
      dbLength: 50,
      dbScale: 0,
      dbNull: true,
      dbPrimary: false,
      dbUnique: false,
    },
  },
  {
    config: {
      label: '附件上传',
      tag: 'q-uploader',
      tagIcon: 'upload',
      layout: 'colFormItem',
      defaultValue: null,
      showLabel: true,
      labelWidth: null,
      required: true,
      span: 6,
      showTip: false,
      buttonText: '点击上传',
      rule: '',
      regList: [],
      changeTag: false,
      fileSize: 2,
      sizeUnit: 'MB',
    },
    slot: {
      'list-type': true,
    },
    action: 'https://jsonplaceholder.typicode.com/posts/',
    disable: false,
    accept: '',
    name: 'file',
    'auto-upload': true,
    'list-type': 'text',
    multiple: false,
    db: {
      dbType: 'varchar',
      dbLength: 255,
      dbScale: 0,
      dbNull: true,
      dbPrimary: false,
      dbUnique: false,
    },
  },
  {
    config: {
      label: '碎片',
      showLabel: false,
      changeTag: false,
      labelWidth: null,
      tag: 'q-chip',
      tagIcon: 'chip',
      span: 3,
      layout: 'colFormItem',
      required: false,
    },
    label: '描述信息',
    color: 'primary',
    textColor: 'white',
    icon: 'directions',
  },
  {
    config: {
      label: '按钮',
      showLabel: false,
      changeTag: false,
      labelWidth: null,
      tag: 'q-btn',
      tagIcon: 'button',
      span: 6,
      layout: 'colFormItem',
      required: false,
      hasDefault: false,
      btnAction: 'save',
    },
    label: '保存',
    dense: true,
    color: 'primary',
    icon: 'save',
    round: false,
    plain: false,
    circle: false,
    disable: false,
  },
  {
    config: {
      label: '按钮切换',
      defaultValue: '1',
      showLabel: true,
      changeTag: false,
      labelWidth: null,
      tag: 'q-btn-toggle',
      tagIcon: 'btn-toggle',
      span: 6,
      layout: 'colFormItem',
      optionSourceType: 'custom',
      required: false,
    },
    options: [{
      label: '选项一',
      value: '1',
    }, {
      label: '选项二',
      value: '2',
    }],
    dense: true,
    unelevated: true,
    toggleColor: 'primary',
    toggleTextColor: 'white',
    color: 'white',
    textColor: 'primary',
    round: false,
    spread: true,
    noCaps: true,
    plain: false,
    circle: false,
    disable: false,
    db: {
      dbType: 'varchar',
      dbLength: 255,
      dbScale: 0,
      dbNull: true,
      dbPrimary: false,
      dbUnique: false,
    },
  },
  {
    config: {
      label: '范围选择',
      defaultValue: {
        min: 20,
        max: 55,
      },
      showLabel: true,
      changeTag: false,
      labelWidth: null,
      tag: 'q-range',
      tagIcon: 'range',
      span: 6,
      layout: 'colFormItem',
      required: false,
    },
    labelAlways: true,
    min: 0,
    max: 100,
    color: 'deep-orange',
    db: {
      dbType: 'varchar',
      dbLength: 255,
      dbScale: 0,
      dbNull: true,
      dbPrimary: false,
      dbUnique: false,
    },
  },
  {
    config: {
      label: '旋钮',
      defaultValue: 50,
      showLabel: true,
      changeTag: false,
      labelWidth: null,
      tag: 'q-knob',
      tagIcon: 'knob',
      span: 2,
      layout: 'colFormItem',
      required: false,
    },
    showValue: true,
    size: '50px',
    min: 0,
    max: 100,
    color: 'orange',
    trackColor: 'grey',
    centerColor: 'white',
    class: 'q-ma-md',
    db: {
      dbType: 'int',
      dbLength: 8,
      dbScale: 0,
      dbNull: true,
      dbPrimary: false,
      dbUnique: false,
    },
  },
  {
    config: {
      label: '分隔条',
      showLabel: false,
      changeTag: false,
      labelWidth: null,
      tag: 'q-separator',
      tagIcon: 'separator',
      span: 12,
      layout: 'colFormItem',
      required: false,
    },
  },
  {
    config: {
      label: '标签',
      showLabel: true,
      changeTag: false,
      labelWidth: null,
      tag: 'q-item-label',
      tagIcon: 'label',
      span: 2,
      layout: 'colFormItem',
      required: false,
    },
  },
  {
    config: {
      label: '图标',
      showLabel: false,
      changeTag: false,
      labelWidth: null,
      tag: 'q-icon',
      tagIcon: 'icon',
      span: 2,
      layout: 'colFormItem',
      required: false,
    },
    name: 'style',
    size: 'xl',
    color: 'primary',
  },
];

export const advanceComponents = [
  {
    config: {
      layout: 'rowFormItem',
      tagIcon: 'row',
      tag: 'row',
      label: '行容器',
      layoutTree: true,
      hasDefault: false,
      span: 12,
    },
    layout: 'default',
    justify: 'justify-start',
    align: 'items-top',
    direction: 'row',
    wrap: 'wrap',
  },
  {
    config: {
      layout: 'tableItem',
      tagIcon: 'table',
      tag: 'table',
      label: '表单表格',
      layoutTree: true,
      hasDefault: false,
      span: 12,
      defaultType: 'custom',
      autoLoadData: true,
      showIndex: true,
      showDelete: true,
      showAdd: true,
      defaultValue: [],
      relatedForm: '',
      relatedColumnList: [],
      relatedFilter: [],
    },
    sub: {
      tableId: 'sub_',
      tableName: '子表',
    },
    layout: 'default',
    justify: 'justify-start',
    align: 'items-top',
    direction: 'row',
    wrap: 'wrap',
  },
  {
    config: {
      label: '用户',
      showLabel: true,
      labelWidth: null,
      tag: 'q-select',
      tagIcon: 'user',
      layout: 'colFormItem',
      span: 6,
      required: true,
      rule: '',
      regList: [],
      changeTag: false,
      hasDefault: false,
      inputType: 'user',
      userList: [],
      roleList: [],
      deptList: [],
      dynamicList: [],
      relatedForm: '',
      relatedColumn: '',
      relatedFilter: [],
    },
    prefix: '',
    suffix: '',
    hint: null,
    hideHint: false,
    outlined: true,
    dense: true,
    optionsDense: true,
    emitValue: true,
    mapOptions: true,
    readonly: false,
    disable: false,
    counter: false,
    clearable: true,
    filterable: false,
    multiple: false,
    options: [],
    db: {
      dbType: 'varchar',
      dbLength: 255,
      dbScale: 0,
      dbNull: true,
      dbPrimary: false,
      dbUnique: false,
    },
  },
  {
    config: {
      label: '部门',
      showLabel: true,
      labelWidth: null,
      tag: 'q-select',
      tagIcon: 'dept',
      layout: 'colFormItem',
      span: 6,
      required: true,
      rule: '',
      regList: [],
      changeTag: false,
      hasDefault: false,
      inputType: 'dept',
      userList: [],
      roleList: [],
      deptList: [],
      dynamicList: [],
      relatedForm: '',
      relatedColumn: '',
      relatedFilter: [],
    },
    prefix: '',
    suffix: '',
    hint: null,
    hideHint: false,
    outlined: true,
    dense: true,
    optionsDense: true,
    emitValue: true,
    mapOptions: true,
    readonly: false,
    disable: false,
    counter: false,
    clearable: true,
    filterable: false,
    multiple: false,
    options: [],
    db: {
      dbType: 'varchar',
      dbLength: 255,
      dbScale: 0,
      dbNull: true,
      dbPrimary: false,
      dbUnique: false,
    },
  },
  {
    config: {
      layout: 'colFormItem',
      tagIcon: 'table',
      tag: 'q-table',
      label: '传统表格',
      hasDefault: false,
      span: 12,
    },
    title: '传统表格',
    slot: {
      top: true,
      bodyCellOpt: true,
    },
    columns: [{
      name: 'id',
      label: '学号',
      field: 'id',
      align: 'center',
    }, {
      name: 'name',
      label: '姓名',
      field: 'name',
      align: 'center',
    }, {
      name: 'opt',
      label: '操作',
      field: 'opt',
      align: 'center',
    }],
    data: [{
      id: 1,
      name: '张无忌',
    }, {
      id: 2,
      name: '周芷若',
    }],
  },
];
