export const optOptions = [{ label: '=', value: 'eq' },
  { label: 'in', value: 'in' },
  { label: '%_', value: 'left_like' },
  { label: '_%', value: 'right_like' },
  { label: 'like', value: 'like' },
  { label: '!=', value: 'ne' },
  { label: '>', value: 'gt' },
  { label: '>=', value: 'ge' },
  { label: '<', value: 'lt' },
  { label: '<=', value: 'le' }];
